apiVersion: v1
kind: List
metadata:
 name: configmap
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    labels:
      openshift.io/cluster-monitoring: "true"
    name: openshift-storage # Enter the namespace where you want to install the OCS Operator.
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: rook-ceph-operator-config
    namespace: openshift-storage # Enter the namespace where you want to install the OCS Operator.
  data:
    ROOK_CSI_KUBELET_DIR_PATH: "/var/data/kubelet"
